#! /bin/tcsh -f

#===============================================================================================================================================================

set wrapperDir = $PWD
set startTime = `date '+%m/%d/%Y %H:%M:%S'`
echo 
echo Wrapper Started at:
echo $startTime
echo
echo This Wrapper will wrap around and run these 3 programs:
#echo This Wrapper will wrap around and run these 4 programs:
echo 1\) fbt3 and PSFavr8
echo 2\) ICORE
echo 3\) MDET
#echo 4\) WPHOTPMC
#echo ================================================================================================================
#echo WARNING\: Elijah is doing testing\/editing to this program \(Oct10 2017\). This script will not work propperly.
#echo ================================================================================================================

if ($# != 3) then
	#Error handling
	#Too many or too little arguments	
	echo "ERROR: not enough arguments:"
	echo "Parameters for wrapper must be in the order:"
	echo 1\) Option 1 or 2 \(1 == Input directory, 2 == Input list\)
	echo 2\) Input directory or list
	echo 3\) Output directory 
	echo "i.e. 'icore_wrapper_executable option InputDir/List OutputDir'" 
	echo 
	echo Exiting...
	exit 
#Option1
else if ($1 == 1) then
	set InputsDir = $2
	set OutputsDir = $3
	echo Inputs directory ==  $InputsDir
	echo Outputs directory == $OutputsDir
	echo "Are these the correct input and output directories? (y/n)"
	set userInput = $<
	
	#Error handling
	#if user input dir wrong
	if($userInput != "Y" && $userInput != "y") then
		echo Please execute program again with full Input Directory path as the 2nd parameter and the Ouput Directory path as your 3rd parameter  
		#TODO actually throw an error instead of just outputing to stdout... output to stderr
		echo
		echo Exiting...	
		exit
	endif
	#if directories dont exist, throw error
	if(! -d $InputsDir) then  
		echo ERROR: Input Directory $InputsDir doest not exist.
		echo	
		echo Exiting...
		exit
	endif
	if (! -d $OutputsDir) then
		echo ERROR: Output Directory $OutputsDir does not exist.
		echo	
		echo Exiting...
		exit
	endif
	
	goto Option1
#Option2
else if ($1 == 2) then
	set InputsList = $2
        set OutputsDir = $3
        echo Inputs list ==  $InputsList
        echo Outputs directory == $OutputsDir
        echo "Is this the correct input list and output directory? (y/n)"
        set userInput = $<
 	
	#Error handling
        #if user input dir wrong
        if($userInput != "Y" && $userInput != "y") then
                echo Please execute program again with full Input List file as the 2nd parameter and the Ouput Directory path as your 3rd parameter
                #TODO actually throw an error instead of just outputing to stdout... output to stderr
                echo
                echo Exiting...
                exit
        endif
        #if directories dont exist, throw error
        if(! -f $InputsList) then
                echo ERROR: Input List file $InputsDir doest not exist.
                echo
                echo Exiting...
                exit
        endif
        if (! -d $OutputsDir) then
                echo ERROR: Output Directory $OutputsDir does not exist.
                echo
                echo Exiting...
                exit
        endif

	goto Option2
else
	#Error handling
	#option 1/2 not second parameter. program exits.
	echo ERROR option 1 or 2 not selected
	echo
	echo Exiting...
	exit
endif




Option1:
#===============================================================================================================================================================	
# links parent and wrapper dir to run "tcsh" and "source SORUCEME" in parent dir
# this assumes tcsh is installed
echo Creating temp files...
cd ..
tcsh & source SOURCEME && cd $wrapperDir

# loops through all of the tiles and executes icore

set FulldepthDir = ${InputsDir}/Fulldepth/

echo Wrapper now starting...

echo
echo

#===============================================================================================================================================================
#fbt3 and PSFavr8 Wrapper

echo
echo
echo 1\) fbt3 and PSFavr8 programs now starting...

#TESTING
#while
foreach RaRaRaDir ($FulldepthDir*/) #for each directory in FulldepthDir, get each RadecIDdir, run wrapper on RadecID tile
	
	foreach RadecIDDir ($RaRaRaDir*/)
	
		echo =============================== start fbt3 and PSFavr8  wrapper loop iteration =================================
 
		set tempSize = `echo $RadecIDDir  | awk '{print length($0)}'`
		@ tempIndex = ($tempSize - 8)
		set RadecID = `echo $RadecIDDir | awk -v startIndex=$tempIndex '{print substr($0,startIndex,8)}'`
		set RaRaRa = `echo $RadecID | awk '{print substr($0,0,3)}'`
	
		echo $RadecIDDir
		echo "RaRaRa == "$RaRaRa
		echo "RadecID == "$RadecID
	
		echo "--------------------------------------- start fbt3 and PSFavr8 wrapper ---------------------------------------"
		
		set preworkINPUTdir = ${FulldepthDir}${RaRaRa}/${RadecID}/
		echo fbt3 and PSFavr8 Input Dir === $preworkINPUTdir
		set preworkOUTPUTdir = ${OutputsDir}/${RaRaRa}/${RadecID}/Full/

		echo calling fbt3 and PSFavr8 on ${RadecID} tile
		
		#TODO make dir for Full, asc, dec	
		mkdir -p ${preworkOUTPUTdir}/Asce
		mkdir -p ${preworkOUTPUTdir}/Desc 
 
		
		# fbt3 call
		/Volumes/CatWISE1/jwf/src/fbt3/fbt3 ${preworkINPUTdir}/unwise-${RadecID}-w1-frames.fits ${RadecID}_w1.txt &
		/Volumes/CatWISE1/jwf/src/fbt3/fbt3 ${preworkINPUTdir}/unwise-${RadecID}-w2-frames.fits ${RadecID}_w2.txt &
		wait
		
		#PSFavr8
		/Volumes/CatWISE1/jwf/src/PSFavr8/PSFavr8 -i /Volumes/CatWISE1/jwf/Focal_Plane_PSFs -o $preworkOUTPUTdir -a1 ${RadecID}_w1.txt -a2 ${RadecID}_w2.txt -t $RadecID -da &
		
		echo Removing w1/w2 txt files created by fbt3
		rm w1.txt
		rm w2.txt
			
		#TODO  make sure the PSF input in icore_template matches with the output file name in psfavr8
			

		#Stops calling programs if number of scripts running is greater than number of threads on CPU
                while(`ps -ef | grep PSFavr8 | wc -l` > 12)
                        #echo IM WATING
			#do nothing
                end
		
		echo fbt3 and PSFavr8 for ${RadecID} done!
		
		echo "---------------------------------------- end fbt3 and PSFavr8 wrapper ----------------------------------------"
		echo ================================ end fbt3 and PSFavr8 wrapper loop iteration =================================
	end
end

#===============================================================================================================================================================

#wait for background processes to finish
wait
echo fbt3 and PSFavr8 wrapper finished!
echo

#===============================================================================================================================================================

echo 2\) ICORE programs now starting...

foreach RaRaRaDir ($FulldepthDir*/) #for each directory in FulldepthDir, get each RadecIDdir, run wrapper on RadecID tile
	
	foreach RadecIDDir ($RaRaRaDir*/)

		echo ===================================== start ICORE wrapper loop iteration =====================================

		set tempSize = `echo $RadecIDDir  | awk '{print length($0)}'`
		@ tempIndex = ($tempSize - 8)
		set RadecID = `echo $RadecIDDir | awk -v startIndex=$tempIndex '{print substr($0,startIndex,8)}'`
		set RaRaRa = `echo $RadecID | awk '{print substr($0,0,3)}'`
		echo Current Directory running Wrapper == $RadecIDDir
		echo "RaRaRa == "$RaRaRa
		echo "RadecID == "$RadecID
	
		echo "-------------------------------------------- start ICORE wrapper ---------------------------------------------"
		
		set INPUTdir = ${FulldepthDir}${RaRaRa}/${RadecID}/
		set OUTPUTdir = ${OutputsDir}/${RaRaRa}/${RadecID}/Full/
		
		echo Current Input Directory === $INPUTdir
		echo Current Output Directory === $OUTPUTdir
		mkdir -p $OUTPUTdir
		mkdir -p ${OUTPUTdir}/ProgramTerminalOutput/
		#===============================================================================================================================================
	
		# Copies icore_template to make an icore_coadd script for w1 and w2
		# NOTE: this assumes "band" variable is in the 4th line of icore_template
		cp  ${wrapperDir}/icore_template ${wrapperDir}/icore_coadd_w1
		cp  ${wrapperDir}/icore_template ${wrapperDir}/icore_coadd_w2
		sed -i --follow-symlinks '4s/1/2/' ${wrapperDir}/icore_coadd_w2
	
		# Sources/Runs Wrapper executables (one for band 1, other for band 2)
		# This should run concurrently/in parallel
		echo Running ICORE for $RadecID
	
	        #TODO: output error message if this doesnt execute!
		echo Running ICORE for bands 1 and 2 in PARALLEL
		(source ${wrapperDir}/icore_coadd_w1 >& ${OUTPUTdir}/ProgramTerminalOutput/icore_w1_output.txt) & 
		(source ${wrapperDir}/icore_coadd_w2 >& ${OUTPUTdir}/ProgramTerminalOutput/icore_w2_output.txt) & 
#		wait

		#echo running ICORE for bands 1 and 2 in GNU PARALLEL
		#parallel ::: 'source ${wrapperDir}/icore_coadd_w2 |& tee ${OUTPUTdir}/wrapper_w2_output.txt' 'source ${wrapperDir}/icore_coadd_w2 |& tee ${OUTPUTdir}/wrapper_w2_output.txt' 
		#(echo '"source '$wrapperDir'/icore_coadd_w1 |& tee '$OUTPUTdir'/wrapper_w1_output.txt"' ; echo '"source '$wrapperDir'/icore_coadd_w2 |& tee '$OUTPUTdir'/wrapper_w2_output.txt\"') | parallel
		#echo done with GNU parallel		
	
		#TODO run in parallel! Fix the background not closing problem
		#echo running ICORE for bands 1 and 2 in SERIES
		#(source ${wrapperDir}/icore_coadd_w1 |& tee "$OUTPUTdir"/wrapper_w1_output.txt)   
		#(source ${wrapperDir}/icore_coadd_w2 |& tee "$OUTPUTdir"/wrapper_w2_output.txt) 
	
		#Stops calling programs if number of scripts running is greater than number of threads on CPU
		while(`ps -ef | grep icore_coadd_w | wc -l` > 12)
                	#do nothing
        	end
			
		echo ICORE for $RadecID done!	
		echo "--------------------------------------------- end ICORE wrapper ----------------------------------------------"
		
		echo ====================================== end ICORE wrapper loop iteration ======================================
	end
end
#===============================================================================================================================================================

#wait for background processes to finish
wait
echo ICORE wrapper finished!
echo

#===============================================================================================================================================================
#MDET Wrapper

echo
echo
echo 3\) MDET programs now starting...

foreach RaRaRaDir ($FulldepthDir*/) #for each directory in FulldepthDir, get each RadecIDdir, run wrapper on RadecID tile
	
	foreach RadecIDDir ($RaRaRaDir*/)
	
		echo ===================================== start MDET wrapper loop iteration ======================================
 
		set tempSize = `echo $RadecIDDir  | awk '{print length($0)}'`
		@ tempIndex = ($tempSize - 8)
		set RadecID = `echo $RadecIDDir | awk -v startIndex=$tempIndex '{print substr($0,startIndex,8)}'`
		set RaRaRa = `echo $RadecID | awk '{print substr($0,0,3)}'`
	
		echo $RadecIDDir
		echo "RaRaRa == "$RaRaRa
		echo "RadecID == "$RadecID
	
		echo "--------------------------------------------- start MDET wrapper ---------------------------------------------"
		
		set MDETInputdir = ${OutputsDir}/${RaRaRa}/${RadecID}/Full/
		echo MDET Input Dir === $MDETInputdir
		
		echo calling MDET on ${RadecID} tile
			
		# MDET call
		(${wrapperDir}/mdet -image1 ${MDETInputdir}/mosaic-w1-int.fits -image2 ${MDETInputdir}/mosaic-w2-int.fits -sigimage1 ${MDETInputdir}/mosaic-w1-unc.fits -sigimage2 ${MDETInputdir}/mosaic-w2-unc.fits -backwindow 400.0 -threshold 2.40 -m -c -outlist ${MDETInputdir}/detlist.tbl -fwhm1 6.000 -fwhm2 6.000 >& ${MDETInputdir}/ProgramTerminalOutput/mdet_output.txt) &	
		
		# MDET with Masks	
		#${wrapperDir}/mdet -image1 ${MDETInputdir}/mosaic-w1-int.fits -image2 ${MDETInputdir}/mosaic-w2-int.fits -sigimage1 ${MDETInputdir}/mosaic-w1-unc.fits -sigimage2 ${MDETInputdir}/mosaic-w2-unc.fits -cmask1 ${MDETInputdir}/1124p045_ac51-w1-cmsk-3.fits -cmask2 ${MDETInputdir}1124p045_ac51-w2-cmsk-3.fits -backwindow 400.0 -threshold 2.40 -m -c -outlist ${MDETInputdir}/detlist.tbl -fwhm1 6.000 -fwhm2 6.000 	
		
		#Stops calling programs if number of scripts running is greater than number of threads on CPU
                while(`ps -ef | grep mdet | wc -l` > 12)
                        #echo IM WATING
			#do nothing
                end
		
		echo MDET for ${RadecID} done!
		
		echo "---------------------------------------------- end MDET wrapper ----------------------------------------------"
		echo ====================================== end MDET wrapper loop iteration =======================================
	end
end

#===============================================================================================================================================================

#wait for background processes to finish
wait
echo MDET wrapper finished!
echo
 
#===============================================================================================================================================================
#WPHOTPMC Wrapper

#echo
#echo
#echo 4\) WPHOTPMC programs now starting...

#foreach RaRaRaDir ($FulldepthDir*/) #for each directory in FulldepthDir, get each RadecIDdir, run wrapper on RadecID tile
	
#	foreach RadecIDDir ($RaRaRaDir*/)
	
#		echo ===================================== start WPHOTPMC wrapper loop iteration ======================================
 
#		set tempSize = `echo $RadecIDDir  | awk '{print length($0)}'`
#		@ tempIndex = ($tempSize - 8)
#		set RadecID = `echo $RadecIDDir | awk -v startIndex=$tempIndex '{print substr($0,startIndex,8)}'`
#		set RaRaRa = `echo $RadecID | awk '{print substr($0,0,3)}'`
	
#		echo $RadecIDDir
#		echo "RaRaRa == "$RaRaRa
#		echo "RadecID == "$RadecID
	
#		echo "--------------------------------------------- start WPHOTPMC wrapper ---------------------------------------------"
		
#		set MDETInputdir = ${OutputsDir}/${RaRaRa}/${RadecID}/Full/
		#set EpochsFramesList = ${OutputsDir}/${RaRaRa}/${RadecID}/frames.list.tbl
		#set PSFdir = ${OutputsDir}/${RaRaRa}/${RadecID}/PSFs/
		#set Coadddir = ${OutputsDir}/${RaRaRa}/${RadecID}/Coadds/
#		echo MDET Input Dir === $MDETInputdir
		
#		echo calling WPHOTPMC on ${RadecID} tile
	
		#WPHOTPMC call
#		set editedMDETInputdir = `echo $MDETInputdir | sed 's/\//\\\//g'`
		#changes MDET output location
#		sed -i --follow-symlinks "16s/.*.*/set mdetfile = ${editedMDETInputdir}detlist.tbl/g" ${wrapperDir}/run_wphotpmc.csh
		#changes frames list	
#		sed -i --follow-symlinks "20s/.*.*/set flist = ${editedMDETInputdir}frames\/frames.list_unwise.tbl/g" ${wrapperDir}/run_wphotpmc.csh	
		#changes PSFs dir
#		sed -i --follow-symlinks "34s/.*.*/set psfdir = ${editedMDETInputdir}/g" ${wrapperDir}/run_wphotpmc.csh	
		#changes coadds list
#		sed -i --follow-symlinks "41s/.*.*/set cname = ${editedMDETInputdir}mosiac/g" ${wrapperDir}/run_wphotpmc.csh
		#changes QA output dir
#                sed -i --follow-symlinks "48s/.*.*/set outQAdir = ${editedMDETInputdir}QAOutputWPHOTPMC/g" ${wrapperDir}/run_wphotpmc.csh
	        #changes WPHOTPMC output dir
#                sed -i --follow-symlinks "53s/.*.*/set outdir = ${editedMDETInputdir}OutputWPHOTPMC/g" ${wrapperDir}/run_wphotpmc.csh
	        #changes WPHOTPMC terminal output file name
#                sed -i --follow-symlinks "58s/.*.*/set terminaloutname = ${editedMDETInputdir}ProgramTerminalOutput\/wphotpmc_output.txt/g" ${wrapperDir}/run_wphotpmc.csh
			
		# run WPHOTPMC
		#${wrapperDir}/run_wphotpmc.csh
		
		#Stops calling programs if number of scripts running is greater than number of threads on CPU
 #               while(`ps -ef | grep wphot | wc -l` > 12)
                        #do nothing
 #               end
		
#		echo WPHOTPMC for ${RadecID} done!
		
		echo "---------------------------------------------- end WPHOTPMC wrapper ----------------------------------------------"
		echo ====================================== end WPHOTPMC wrapper loop iteration =======================================
	end
end
#===============================================================================================================================================================

#wait for background processes to finish
#wait
#echo WPHOT wrapper finished!
#echo
#===============================================================================================================================================================
goto Done

Option2:
echo HelloWorld
goto Done


Done:		
# Deletes and cleans up files
cd $wrapperDir
echo Deleting Wrapper temp files...
source icore_cleanup_wrapper
echo Done deleting!


#===============================================================================================================================================================
echo Wrapper finished!
set endTime = `date '+%m/%d/%Y %H:%M:%S'`
echo
echo Wrapper Ended at:
echo $endTime
echo
